public class CenterOfMass {

public static Point centerOfMass(Point[] points){
    double = x;
    double = y;
    this.x = x;
    this.y = y;
    
    public static Point centerOfMass(Point[] points) {
        double sumOfX = 0;
        double sumOfY = 0;

    for (Point point : points) {
            sumOfX = point.x 
            sumOfY = point.y 
        }
    double centerX = sumOfX / points.length;
    double centerY = sumOfY / points.length;
    return new Point(centerX, centerY);
}
} 
}
